server:
  port: 8768

spring: 
  application:
    name: admin-client
  boot:
    admin:
      client:
        url: http://localhost:8769

eureka: 
  client:
    serviceUrl:
      defaultZone: http://boot:boot123@127.0.0.1:8761/eureka/
    instance:
      prefer-ip-address: true
      instance-id: ${spring.application.name}:${server.port}
  
management: 
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS