server:
  context-path: /uaa
  port: 8989
  
spring:
  application:
    name: boot-microservice-oauth2
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/boot?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  typeAliasesPackage: org.spring.springboot.domain

eureka:
  client:
    serviceUrl:
      defaultZone: http://boot:boot123@127.0.0.1:8761/eureka/
    instance:
      prefer-ip-address: true
      instance-id: ${spring.application.name}:${server.port}
      
security:
  oauth2:
    resource:
      filter-order: 3
