server: 
  port: 8769
  
spring:
  application:
    name: admin-server
  security:
    user:
      name: boot
      password: boot123
         
eureka: 
  client:
    serviceUrl:
      defaultZone: http://boot:boot123@127.0.0.1:8761/eureka/
    instance:
      prefer-ip-address: true
      instance-id: ${spring.application.name}:${server.port}
      metadata-map:
        user.name: ${spring.security.user.name}
        user.password: ${spring.security.user.password}

management: 
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS