server:
  port: 9221

spring:
  redis: 
    host: 127.0.0.1
    port: 6379
    password: 
    database: 0
    pool: 
      max-active: 8
      max-wait: -1
      max-idle: 500
      min-idle: 0
    timeout: 200